# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-04-27 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
