# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-04-27 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='info',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
